"""PDF rendering for CIO Insights publications.

This module owns ``markdown_to_pdf_bytes`` — the same function that
previously lived in ``app.py``. It is imported from there so the
on-demand "Download PDF" button in Streamlit and the scheduled
publication flow share a single rendering path.

No behavioral changes from the original — pure relocation.
"""

from __future__ import annotations

import io
import os
import re
from pathlib import Path


DEFAULT_APP_BASE_URL = "https://pensionplanintelligence.onrender.com"


def absolute_url(href: str) -> str:
    """Prepend APP_BASE_URL to relative links so PDFs work outside the app.

    Falls back to the deployed Render service so PDFs generated by a
    cron job — which has no in-browser context — still link back to
    the public site.
    """
    if href.startswith(("http://", "https://", "mailto:")):
        return href
    base = (os.environ.get("APP_BASE_URL") or DEFAULT_APP_BASE_URL).rstrip("/")
    if href.startswith("?"):
        return f"{base}/{href}"
    if href.startswith("/"):
        return f"{base}{href}"
    return f"{base}/{href}"


def markdown_to_pdf_bytes(title: str, date_str: str, markdown_text: str) -> bytes:
    """Convert a markdown note to a PDF using reportlab.

    Relative links (e.g. ``?doc=42``) are rewritten to absolute URLs
    using ``APP_BASE_URL`` so they resolve correctly when the PDF is
    opened outside the app.
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    from reportlab.lib import colors

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=20 * mm, bottomMargin=20 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "NoteTitle", parent=styles["Heading1"],
        fontSize=16, spaceAfter=4, textColor=colors.HexColor("#003366"),
    )
    date_style = ParagraphStyle(
        "NoteDate", parent=styles["Normal"],
        fontSize=9, textColor=colors.grey, spaceAfter=10,
    )
    h2_style = ParagraphStyle(
        "NoteH2", parent=styles["Heading2"],
        fontSize=12, spaceBefore=10, spaceAfter=4,
        textColor=colors.HexColor("#003366"),
    )
    body_style = ParagraphStyle(
        "NoteBody", parent=styles["Normal"],
        fontSize=10, leading=14, spaceAfter=6,
    )
    bullet_style = ParagraphStyle(
        "NoteBullet", parent=body_style,
        leftIndent=12, bulletIndent=0,
    )

    story = [
        Paragraph(title, title_style),
        Paragraph(date_str, date_style),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#003366"), spaceAfter=8),
    ]

    for line in markdown_text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("---") or stripped.startswith("*Generated"):
            continue
        if stripped.startswith("## "):
            story.append(Spacer(1, 4))
            story.append(Paragraph(stripped[3:], h2_style))
        elif stripped.startswith("# "):
            pass  # already in title
        elif stripped.startswith("- ") or stripped.startswith("* "):
            text = stripped[2:]
            text = re.sub(
                r"\[([^\]]+)\]\(([^)]+)\)",
                lambda m: f'<a href="{absolute_url(m.group(2))}" color="blue">{m.group(1)}</a>',
                text,
            )
            text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
            text = re.sub(r"\*(.+?)\*", r"<i>\1</i>", text)
            story.append(Paragraph(f"• {text}", bullet_style))
        else:
            text = re.sub(
                r"\[([^\]]+)\]\(([^)]+)\)",
                lambda m: f'<a href="{absolute_url(m.group(2))}" color="blue">{m.group(1)}</a>',
                stripped,
            )
            text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
            text = re.sub(r"\*(.+?)\*", r"<i>\1</i>", text)
            story.append(Paragraph(text, body_style))

    doc.build(story)
    return buf.getvalue()


def write_pdf(publication_id: int, title: str, date_str: str,
              markdown_text: str, out_dir: Path | None = None) -> Path:
    """Render the markdown to PDF and write it to disk.

    Returns the absolute path to the written PDF. The default output
    directory is ``notes/pdfs/`` next to the existing markdown notes.
    """
    if out_dir is None:
        out_dir = Path(__file__).resolve().parent.parent / "notes" / "pdfs"
    out_dir.mkdir(parents=True, exist_ok=True)
    pdf_path = out_dir / f"publication_{publication_id}.pdf"
    pdf_path.write_bytes(markdown_to_pdf_bytes(title, date_str, markdown_text))
    return pdf_path
