"""PDF rendering for Insights publications.

This module owns ``markdown_to_pdf_bytes`` — the same function that
previously lived in ``app.py``. It is imported from there so the
on-demand "Download PDF" button in Streamlit and the scheduled
publication flow share a single rendering path.

No behavioral changes from the original — pure relocation.
"""

from __future__ import annotations

import io
import os
import re
from pathlib import Path


DEFAULT_APP_BASE_URL = "https://pensionplanintelligence.onrender.com"


def absolute_url(href: str) -> str:
    """Prepend APP_BASE_URL to relative links so PDFs work outside the app.

    Falls back to the deployed Render service so PDFs generated by a
    cron job — which has no in-browser context — still link back to
    the public site.
    """
    if href.startswith(("http://", "https://", "mailto:")):
        return href
    base = (os.environ.get("APP_BASE_URL") or DEFAULT_APP_BASE_URL).rstrip("/")
    if href.startswith("?"):
        return f"{base}/{href}"
    if href.startswith("/"):
        return f"{base}{href}"
    return f"{base}/{href}"


def markdown_to_pdf_bytes(title: str, date_str: str, markdown_text: str) -> bytes:
    """Convert a markdown note to a PDF using reportlab.

    Relative links (e.g. ``?doc=42``) are rewritten to absolute URLs
    using ``APP_BASE_URL`` so they resolve correctly when the PDF is
    opened outside the app.
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle,
    )
    from reportlab.lib import colors

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=20 * mm, bottomMargin=20 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "NoteTitle", parent=styles["Heading1"],
        fontSize=16, spaceAfter=4, textColor=colors.HexColor("#003366"),
    )
    date_style = ParagraphStyle(
        "NoteDate", parent=styles["Normal"],
        fontSize=9, textColor=colors.grey, spaceAfter=10,
    )
    h2_style = ParagraphStyle(
        "NoteH2", parent=styles["Heading2"],
        fontSize=12, spaceBefore=10, spaceAfter=4,
        textColor=colors.HexColor("#003366"),
    )
    body_style = ParagraphStyle(
        "NoteBody", parent=styles["Normal"],
        fontSize=10, leading=14, spaceAfter=6,
    )
    bullet_style = ParagraphStyle(
        "NoteBullet", parent=body_style,
        leftIndent=12, bulletIndent=0,
    )

    cell_style = ParagraphStyle(
        "NoteCell", parent=body_style,
        fontSize=8, leading=10, spaceAfter=0,
    )

    def inline_html(text: str) -> str:
        text = re.sub(
            r"\[([^\]]+)\]\(([^)]+)\)",
            lambda m: f'<a href="{absolute_url(m.group(2))}" color="blue">{m.group(1)}</a>',
            text,
        )
        text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
        text = re.sub(r"\*(.+?)\*", r"<i>\1</i>", text)
        return text

    def split_row(s: str) -> list[str]:
        inner = s.strip().strip("|")
        return [c.strip() for c in inner.split("|")]

    def is_table_separator(s: str) -> bool:
        if "|" not in s:
            return False
        return all(re.fullmatch(r":?-{3,}:?", c) for c in split_row(s) if c)

    story = [
        Paragraph(title, title_style),
        Paragraph(date_str, date_style),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#003366"), spaceAfter=8),
    ]

    lines = markdown_text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Markdown table
        if (
            "|" in stripped
            and i + 1 < len(lines)
            and is_table_separator(lines[i + 1])
        ):
            headers = split_row(stripped)
            i += 2
            rows: list[list[str]] = []
            while i < len(lines) and "|" in lines[i] and lines[i].strip():
                rows.append(split_row(lines[i]))
                i += 1
            data = [[Paragraph(f"<b>{inline_html(h)}</b>", cell_style) for h in headers]]
            data.extend(
                [Paragraph(inline_html(c), cell_style) for c in row]
                for row in rows
            )
            tbl = Table(data, repeatRows=1, hAlign="LEFT")
            tbl.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#003366")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("LINEBELOW", (0, 0), (-1, 0), 1, colors.HexColor("#003366")),
                ("LINEBELOW", (0, 1), (-1, -1), 0.25, colors.HexColor("#cccccc")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]))
            story.append(Spacer(1, 4))
            story.append(tbl)
            story.append(Spacer(1, 6))
            continue

        if not stripped or stripped.startswith("---") or stripped.startswith("*Generated"):
            i += 1
            continue
        if stripped.startswith("## "):
            story.append(Spacer(1, 4))
            story.append(Paragraph(stripped[3:], h2_style))
        elif stripped.startswith("# "):
            pass  # already in title
        elif stripped.startswith("- ") or stripped.startswith("* "):
            story.append(Paragraph(f"• {inline_html(stripped[2:])}", bullet_style))
        else:
            story.append(Paragraph(inline_html(stripped), body_style))
        i += 1

    doc.build(story)
    return buf.getvalue()


def write_pdf(publication_id: int, title: str, date_str: str,
              markdown_text: str, out_dir: Path | None = None) -> Path:
    """Render the markdown to PDF and write it to disk.

    Returns the absolute path to the written PDF. The default output
    directory is ``notes/pdfs/`` next to the existing markdown notes.
    """
    if out_dir is None:
        out_dir = Path(__file__).resolve().parent.parent / "notes" / "pdfs"
    out_dir.mkdir(parents=True, exist_ok=True)
    pdf_path = out_dir / f"publication_{publication_id}.pdf"
    pdf_path.write_bytes(markdown_to_pdf_bytes(title, date_str, markdown_text))
    return pdf_path
